[book]
authors = ["Chen-Pang He"]
language = "en"
src = "src"
title = "Strawberry Polish Club"

[output.html]
additional-css = ["style.css"]
site-url = "https://polish.club/"
git-repository-url = "https://github.com/jdh8/polish.club"
edit-url-template = "https://github.com/jdh8/polish.club/edit/main/{path}"
smart-punctuation = true

[preprocessor.replace]

[preprocessor.replace.list]
"♠" = "<span class='♠'>♠</span>"
"♥" = "<span class='♥'>♥</span>"
"♦" = "<span class='♦'>♦</span>"
"♣" = "<span class='♣'>♣</span>"
"(R)" = "<abbr title='relay'>(R)</abbr>"

[preprocessor.abbr]

[preprocessor.abbr.list]
BML = "Bridge Bidding Markup Language"
BTU = "Bridge Taiwan University"
COG = "choice of games"
NLTC = "New Losing Trick Count"

# WBF-listed abbreviations
# http://www.worldbridge.org/wp-content/uploads/2017/04/Guidetocompletion.pdf
AGG = "aggressor"
ADV = "advancer"
ART = "artificial"
ATT = "attitude"
BAL = "balanced"
BW = "Blackwood"
CB = "checkback"
COMP = "competitive"
CONC = "concentrated"
CONST = "constructive"
CTRL = "control"
DBL = "double"
DISC = "discourage"
ENC = "encourage"
FRAG = "fragment"
F = "forcing"
F1 = "forcing one round"
F2NT = "forcing to 2NT"
FG = "forcing to game (3NT)"
4SF = "4th suit forcing"
4SFG = "4th suit forcing to game"
4SF1 = "4th suit forcing one round"
FREQ = "frequent"
"G/T" = "game try"
HCP = "high card points"
INV = "invitational"
INQ = "inquiry"
KCB = "Keycard Blackwood"
"L/D" = "lead directing"
LEB = "Lebensohl"
LHO = "the opponent on your left"
LIM = "limit raise"
"L/S" = "long suit"
MM = "major suits"
mm = "minor suits"
MAX = "maximum/maximal"
MIN = "minimum"
NAT = "natural"
NEG = "negative"
NEU = "neutral"
NF = "non-forcing"
NV = "non-vulnerable"
OPPT = "opponent"
OPT = "optional"
"O/S" = "outside"
"O/C" = "overcall"
"P/C" = "pass or correct"
PEN = "penalty"
PH = "passed hand"
PRE = "preemptive"
PUP = "puppet (to)"
QUANT = "quantitative"
RDBL = "redouble"
RD = "redouble"
RESP = "responsive"
REV = "reverse"
RHO = "the opponent on your right"
RKCB = "Roman Keycard Blackwood"
"R/O" = "reopening"
"S/P" = "suit preference"
"S/A" = "suit agreement"
"S/O" = "signoff"
SOL = "solid"
S-SOL = "semi-solid"
SPL = "Splinter"
"S/S" = "short suit"
"S/T" = "slam try"
STAY = "Stayman"
STR = "strong"
SUPP = "support"
"T/O" = "takeout"
TRF = "transfer"
UNBAL = "unbalanced"
UNT = "unusual notrump"
VUL = "vulnerable"
WJO = "weak jump overcall"
WJS = "weak jump shift"
WK = "weak"
